[package]

name = "nullable"
version = "0.0.1"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-nullable.git"
description = "A wrapper around raw pointers with lifetime tracking."
readme = "README.md"
license = "MIT"

